name: Pack WP Plugin
description: Pack WP plugin files into a zip file that is ready for deployment
branding:
  icon: archive
  color: blue
inputs:
  plugin_slug:
    description: The slug of the plugin to pack
    required: true
  output_file:
    description: The name of the output file
    required: false
    default: /tmp/release.zip

runs:
  using: composite
  steps:
    - env:
        ACTION_PLUGIN_SLUG: ${{ inputs.plugin_slug }}
        ACTION_OUTPUT_FILE: ${{ inputs.output_file }}
      id: plugin_pack
      run: |
        ${{ github.action_path }}/packer-action.bash
      shell: bash
